### PR TITLE
fix: only decorate late spans when configured to do so

### LINKED ISSUE #642: Mark late spans only when AddRuleReasonToTrace is configured
Today it does it unconditionally.

### PR DESCRIPTION
**Pull request by fchikwekwe**
Closes #642 

Check that late arriving spans are configured with `AddRuleReasonToTrace` before marking them late.

### CODE REVIEW

File: config/file_config.go [hunk 1]
```diff
@@ -350,6 +353,14 @@ func (f *fileConfig) validateGeneralConfigs() error {
 	default:
 		return fmt.Errorf("invalid CacheOverrunStrategy: '%s'", st)
 	}
+
+	stressReliefConfig := f.GetStressReliefConfig()
```
Comment (TylerHelmuth) [inline config/file_config.go:357]: Can you remove these changes and save them for the other PR?

**Review by TylerHelmuth — COMMENTED** [review]
One cleanup request, otherwise LGTM.

File: config/file_config.go (hunk 1 above)
Comment (fchikwekwe) [reply config/file_config.go]: Oh, not sure how this happened. Accidental. Should be fixed now.

**Review by TylerHelmuth — APPROVED** [review]
