### PR TITLE
Consolidate honeycomb metrics to use single lock & fix concurrent read/write

### LINKED ISSUE #512: Honeycomb metrics panics with concurrent read/write error
**Versions**

- Go: 1.18
- Refinery: 1.15.0

**Steps to reproduce**
Running refinery for an extended time period using Honeycomb metrics can run into this issue. The problem is a mutex lock is used to register and collect metrics but the functions used to update metrics values doesn't use the generic locks, which can lead to a concurrent read / write error.

For example, the [Counter](https://github.com/honeycombio/refinery/blob/main/metrics/honeycomb.go#L323) func here doesn't acquire the lock before attempting to retrieve a metric from the registers counters map.

### PR DESCRIPTION
**Pull request by MikeGoldsmith**
## Which problem is this PR solving?
Honeycomb metrics currently utilises 3 locks, one for each map of counters, gauges and histograms and is unnecessary. In addition, the locks were only used when registering each metric and collecting metrics values - they were missing the lock to retrieve an entry for updating which risks a read / write error.

This PR updates honeycomb metrics to utilise a single lock that is used to control all three types of metrics and is also used when attempting to retrieve a metric from a map.

- Fixes #512 

## Short description of the changes
- Consolidate the 3 locks into a single lock
- Use lock when attempting to retrieve an existing metric from one of the maps to prevent concurrent read / write panics

### CODE REVIEW

File: metrics/honeycomb.go [hunk 1]
```diff
@@ -228,26 +226,23 @@ func (h *HoneycombMetrics) reportToHoneycommb(ctx context.Context) {
 				"api_host": ev.APIHost,
 				"dataset":  ev.Dataset,
 			}
-			h.countersLock.Lock()
```
Comment (vreynolds) [inline metrics/honeycomb.go:231]: removing individual locks would make the entire function block for the whole reporting loop -- would that slow things down?

File: metrics/honeycomb.go [hunk 2]
```diff
@@ -23,12 +23,10 @@ type HoneycombMetrics struct {
 	UpstreamTransport *http.Transport `inject:"upstreamTransport"`
 	Version           string          `inject:"version"`
 
-	countersLock   sync.Mutex
-	counters       map[string]*counter
-	gaugesLock     sync.Mutex
-	gauges         map[string]*gauge
-	histogramsLock sync.Mutex
-	histograms     map[string]*histogram
+	lock       sync.Mutex
```
Comment (vreynolds) [inline metrics/honeycomb.go:26]: this should be a RWLock

File: metrics/honeycomb.go [hunk 3]
```diff
@@ -281,10 +276,11 @@ func average(vals []float64) float64 {
 }
 
 func (h *HoneycombMetrics) Register(name string, metricType string) {
+	h.lock.Lock()
```
Comment (vreynolds) [inline metrics/honeycomb.go:279]: there is a lock acquired in the parent function. I _think_ if parent does a Read lock and here it does a Write lock, it will not deadlock, but needs to be verified

Comment (vreynolds) [reply metrics/honeycomb.go:279]: this was helpful in my past journey with deadlocks: https://github.com/sasha-s/go-deadlock

File: metrics/honeycomb.go (hunk 1 above)
Comment (MikeGoldsmith) [reply metrics/honeycomb.go:231]: I don't think it will have much of an affect. Most of the time we expect to be using read locks only (collect / updating existing metric values).

We use a write lock when adding new metrics (register).

File: metrics/honeycomb.go (hunk 3 above)
Comment (MikeGoldsmith) [reply metrics/honeycomb.go:279]: Yup, you're right. I've refactored to use a RWLock and made sure we release the read lock before attempting to get a write lock.

File: metrics/honeycomb.go [hunk 4]
```diff
@@ -283,75 +278,89 @@ func average(vals []float64) float64 {
...
-func (h *HoneycombMetrics) Count(name string, n interface{}) {
-	count, ok := h.counters[name]
+// getOrAdd attempts to retrieve a (generic) metric from the provided map by name, wrapping the read operation
+// with a read lock (RLock). If the metric is not present in the map, it aquire a write lock and executes
+// create function and add it's to the map.
+func getOrAdd[T *counter | *gauge | *histogram](lock *sync.RWMutex, name string, metrics map[string]T, createMetric func(name string) T) T {
+	// attempt to get metric by name using read lock
+	lock.RLock()
+	metric, ok := metrics[name]
+	lock.Unlock()
```
Comment (vreynolds) [inline metrics/honeycomb.go:298]:
```suggestion
	lock.RUnlock()
```

**Review by vreynolds — CHANGES_REQUESTED** [review]
LGTM, one small change for the read unlock

**Review by vreynolds — APPROVED** [review]
🔒 🎇

File: metrics/honeycomb.go [hunk 5]
```diff
@@ -283,75 +278,89 @@ func average(vals []float64) float64 {
...
+	return metric
+}
+
+func createCounter(name string) *counter {
+	return &counter{
+		name: name,
+	}
+}
+
+func createGague(name string) *gauge {
```
Comment (JamieDanielson) [inline metrics/honeycomb.go:324]:
```suggestion
func createGauge(name string) *gauge {
```
drive-by sorry! Suggest Rename Symbol

File: metrics/honeycomb.go [hunk 6]
```diff
@@ -283,75 +278,89 @@ func average(vals []float64) float64 {
...
 	h.Count(name, 1)
 }
 
 func (h *HoneycombMetrics) Gauge(name string, val interface{}) {
-	gauge, ok := h.gauges[name]
-	if !ok {
-		h.Register(name, "gauge")
-		gauge = h.gauges[name]
-	}
+	gauge := getOrAdd(&h.lock, name, h.gauges, createGague)
```
Comment (JamieDanielson) [inline metrics/honeycomb.go:351]:
```suggestion
	gauge := getOrAdd(&h.lock, name, h.gauges, createGauge)
```
(with function rename)

File: metrics/honeycomb.go [hunk 7]
```diff
@@ -283,75 +278,89 @@ func average(vals []float64) float64 {
...
-		h.gaugesLock.Lock()
-		defer h.gaugesLock.Unlock()
-		_, ok := h.gauges[name]
-		if !ok {
-			newGauge := &gauge{
-				name: name,
-			}
-			h.gauges[name] = newGauge
-		}
+		getOrAdd(&h.lock, name, h.gauges, createGague)
```
Comment (JamieDanielson) [inline metrics/honeycomb.go:283]:
```suggestion
		getOrAdd(&h.lock, name, h.gauges, createGauge)
```
(with function rename)

**Review by JamieDanielson — APPROVED** [review]
This looks great! I left a few tiny suggestions as I went through, mostly just for clarification 👍
