### PR TITLE
fix: Put a limit on the size of sampler keys

### LINKED ISSUE #1363: Protect against giant sample keys
Imagine a large trace with thousands of spans, one for each user, and someone accidentally sets up the key fields for the sampler to include a high-cardinality field like user ID. The value of the sampler key would be an enormous string containing every user ID. 

We think we saw this happen today. We should protect against it by limiting the size of the key, most likely by limiting the number of items that can be placed into the key.

### PR DESCRIPTION
**Pull request by kentquirk**
## Which problem is this PR solving?

- If someone sends a big trace where one of the sampler keys is a high-cardinality field, Refinery could generate a huge sampler key value. This causes problems both for refinery but also the downstream telemetry. Let's not do that.

## Short description of the changes

- Put a limit of 100 unique values to make up any one sampler key. Even that is big and probably useless but it should avoid any real use cases. 
- Add a test to show it works.

Fixes #1363

### CODE REVIEW

File: sample/trace_key.go [hunk 1]
```diff
@@ -42,16 +43,29 @@ func (d *traceKey) build(trace *types.Trace) string {
...
 	spans := trace.GetSpans()
+	uniques := generics.NewSetWithCapacity[string](maxKeyLength)
+outer:
 	for _, field := range d.fields {
 		for _, span := range spans {
 			if val, ok := span.Data[field]; ok {
-				fieldCollector[field] = append(fieldCollector[field], fmt.Sprintf("%v", val))
+				v := fmt.Sprintf("%v", val)
+				uniques.Add(v)
+				if len(uniques) >= maxKeyLength {
```
Comment (MikeGoldsmith) [inline sample/trace_key.go:60]: We don't use the uniques set for anything other than counting, could we just use simple integer counter instead?

File: sample/trace_key.go [hunk 2]
```diff
@@ -42,16 +43,29 @@ func (d *traceKey) build(trace *types.Trace) string {
...
+					break outer
```
Comment (MikeGoldsmith) [inline sample/trace_key.go:61]: We should log that the key exceeded the configured max so we know it's stopped looking for additional keys.

File: sample/trace_key.go [hunk 3]
```diff
@@ -42,16 +43,29 @@ func (d *traceKey) build(trace *types.Trace) string {
 	// if they happen multiple times.
 	fieldCollector := make(map[string][]string)
 
+	// once a key gets this many unique values, it's off the charts in terms of uniqueness
+	// so we just stop looking for more.
+	// This is a safety valve to prevent us from someone sending a high-cardinality field
+	// in a giant trace.
+	const maxKeyLength = 100
```
Comment (MikeGoldsmith) [inline sample/trace_key.go:50]: Probably for the future if the need arises, but this might be a nice configuration option in the future.

**Review by MikeGoldsmith — CHANGES_REQUESTED** [review]
Makes sense in general, but I think a generic set to hold the keys is a bit too much. Can we simplify to an int counter?

File: sample/trace_key.go (hunk 1 above)
Comment (kentquirk) [reply sample/trace_key.go:64]: I had done it that way originally, but the problem is that it's OK to have 1000 instances of a low-cardinality field since we only keep one of them. I just noticed, though, that fieldCollector can still get really large in that situation, so I've just added some code that actually checks that we have a new value before we add it, which will prevent fieldCollector from getting big.

File: sample/trace_key.go (hunk 2 above)
Comment (kentquirk) [reply sample/trace_key.go:68]: OK; the function here doesn't have access to a logger, so I had it return the key size it's using and log if it is the max value.

It occurs to me that we could now make a metric out of this, but I don't have time to do that. Please feel free if you think that's a good idea.

File: sample/trace_key.go (hunk 3 above)
Comment (MikeGoldsmith) [reply sample/trace_key.go]: Created a follow-up issue to track adding in the future if we decide to do it.

File: sample/trace_key.go (hunk 2 above)
Comment (MikeGoldsmith) [reply sample/trace_key.go:68]: Created a follow-up issue to track adding in the future if we decide to do it.

**Review by MikeGoldsmith — APPROVED** [review]
