### PR TITLE
fix: add missing metrics fields

### LINKED ISSUE #801: OTel metrics is missing a few fields
Report through support:

With legacy metrics in Refinery 2.0, we get [memory_in_use](https://github.com/honeycombio/refinery/blob/f295a8cbe2c49e5ad3a1e5855db21c3b3209f570/metrics/legacy.go#L137C32-L137C44) and hostname out of the box. But a customer who just rolled over to OTel metrics isn't seeing these fields come in. 

Turns out these fields are dynamically injected into legacy metrics by a mechanism in libhoney. We need to also do this in otel metrics.

### PR DESCRIPTION
**Pull request by kentquirk**
## Which problem is this PR solving?

- Fixes #801. OTelMetrics was missing some fields that were present in LegacyMetrics. This adds them.
- Adds new sample rate metrics

## Short description of the changes

- Add mechanism that adds the dynamic fields to otel.
- Add some histograms for aggregate sample rate and kept sample rate.

### CODE REVIEW

File: metrics/otel_metrics.go [hunk 1]
```diff
@@ -105,10 +107,19 @@ func (o *OTelMetrics) Start() error {
...
+		hostname = "unknown: " + err.Error()
+	} else {
+		hostname = hn
+	}
+
 	res, err := resource.New(ctx,
 		resource.WithAttributes(resource.Default().Attributes()...),
 		resource.WithAttributes(attribute.KeyValue{Key: "service.name", Value: attribute.StringValue("refinery")}),
 		resource.WithAttributes(attribute.KeyValue{Key: "service.version", Value: attribute.StringValue(o.Version)}),
+		resource.WithAttributes(attribute.KeyValue{Key: "hostname", Value: attribute.StringValue(hostname)}),
```
Comment (TylerHelmuth) [inline metrics/otel_metrics.go:122]: Can we use the semantic convention name `host.name`: https://github.com/open-telemetry/semantic-conventions/blob/main/docs/resource/host.md#host

File: metrics/otel_metrics.go [hunk 2]
```diff
@@ -124,6 +135,46 @@ func (o *OTelMetrics) Start() error {
...
+	if err != nil {
+		return err
+	}
+	o.gauges[name] = g
+
+	name = "memory_inuse"
+	// This is just reporting the gauge we already track under a different name.
+	var fmem metric.Float64Callback = func(_ context.Context, result metric.Float64Observer) error {
+		o.lock.RLock()
+		v, _ := o.Get("memory_heap_allocation")
```
Comment (TylerHelmuth) [inline metrics/otel_metrics.go:155]: What is the value of `v` if this returns an error (I'm assuming `_` is an error)?  Do we need to capture that error?

File: metrics/otel_metrics.go (hunk 1 above)
Comment (kentquirk) [reply metrics/otel_metrics.go:122]: we could add that as a duplicate, but there are TONS of boards and queries using "hostname". I'd be very reluctant to change it. I suppose we could do it differently for OTel metrics vs legacy metrics, but we'd definitely have to tell people we did it.

File: metrics/otel_metrics.go (hunk 2 above)
Comment (kentquirk) [reply metrics/otel_metrics.go:155]: It's not an error, it's an "ok" value telling you that the value you queried was in the dataset. v will be 0 in that case, which should never occur because this is duplicating the other metric. Get is basically just a map query, but the ok value is not optional in that case. I mean, I could return a "can't happen" error here, but 0 is probably better.

File: metrics/otel_metrics.go [hunk 3]
```diff
@@ -124,6 +135,46 @@ func (o *OTelMetrics) Start() error {
...
+		result.Observe(v)
+		o.lock.RUnlock()
```
[the remark this answers is not in the document]
Comment (kentquirk) [reply metrics/otel_metrics.go:157]: The resource is usually unlocked; it's competing locks that cause the problem. 

However, I realized in looking at it that Get is already doing an RLock, so this one is redundant. Removing it.

File: metrics/otel_metrics.go (hunk 1 above)
Comment (TylerHelmuth) [reply metrics/otel_metrics.go:123]: I forgot the other metrics were already using hostname. Duplicating is best.

**Review by TylerHelmuth — APPROVED** [review]
